name: unpub_web
description: A web app that uses AngularDart Components
version: 1.0.0
publish_to: none
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  angular: ^7.0.2
  angular_forms: ^4.0.1
  angular_router: ^3.0.1
  http: ^1.2.2
  markdown: ^7.3.0
  unpub_api:
    path: ../unpub/lib/unpub_api
dev_dependencies:
  build_runner: ^2.4.14
  build_web_compilers: ^4.1.1
