name: unpub
description: Self-hosted private Dart Pub server for Enterprise, with a simple web interface to search and view packages information.
version: 3.0.0-dev.0
homepage: https://github.com/bytedance/unpub
environment:
  sdk: ">=3.3.0 <4.0.0"
executables:
  unpub: unpub
dependencies:
  args: ^2.6.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  http_parser: ^4.1.2
  http: ^1.2.2
  archive: ^3.6.1
  logging: ^1.3.0
  meta: ^1.16.0
  googleapis: ^13.2.0
  yaml: ^3.1.3
  pub_semver: ^2.1.5
  json_annotation: ^4.9.0
  mongo_dart: ^0.10.4
  mime: ^2.0.0
  intl: ^0.20.1
  path: ^1.9.1
  collection: ^1.19.1
  shelf_cors_headers: ^0.1.5
dev_dependencies:
  test: ^1.25.14
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  shelf_router_generator: ^1.1.1
  chunked_stream: ^1.4.2
